### ISSUE TITLE
GroupRepository 관련 Todo

### ISSUE THREAD

**Issue by soopeach** [boostcampwm-2022/android05-MoGakRun#18]
## 🫣 관련 PR

- data layer의 GroupRepositoryImpl 일부 구현 
#12  
- 운동 시작 및 종료 알림들을 받아오는 Flow구현, GroupRepository에 exitGroup 추가
 #16 

## 😲 개요

- [ ] data에서 사용하는 리터럴 제거
- [ ] domain에 Enum class로 Exception 묶어두기
- [ ] Exception 처리방법 공부하기
- [ ] UserResponse.kt 에 있는 "-" 상수로 변경하기
- [x] UserResponse.kt 에 있는 String.toRule() 옮기기
- [x] toRule() 및 Rule.toString() 사용할 때 규칙이 없는 경우 처리
- [x] RepositoryImpl 들 @Binds로 주입하기
- [x] GroupRepositoryImpl의 exitGroup 메서드 수정
  -  `return groupDataSource.joinGroup(uid, groupId)` -> `groupDataSource.exitGroup(uid, groupId)`
