### ISSUE TITLE
내 그룹 탭 임시 구현을 완벽 구현으로 바꾸기위한 TODO

### ISSUE THREAD

**Issue by soopeach** [boostcampwm-2022/android05-MoGakRun#28]
## 🫣 관련 PR

- 내 그룹 탭 임시 구현 #26 

## 😲 개요

- observe 관련(presentation/../ComunityItemFragment.kt)
  - [x] `init 블럭 삭제`
  - [x] `initView() - onViewCreated()에서 실행 `
  (여기서 repeatWhenUiStarted를 직접 열어서 collect하기)

- 컨벤션 관련(presentation/../ComunityItemFragment.kt)
  - [x] `setMyGroupAdapter 내부의 adapter 변수명 myGroupAdapter로 변경`
  (presentation/../ComunityItemFragment.kt)
  - [x] `event() 메서드명 emitEvent()로 변경`
    (presentation/../CommunityItemViewModel.kt)

- [x] `AccountRepository가 구현되면 AccountRepository에서 uid를 얻어온 후 해당 uid로 그룹들 정보를 가져오도록 변경`(domain/../GetMyGroupListUseCase.kt)
- [x] `getMyGroupListFlow 코드 이쁘게 개선`(data/../UserDataSource.kt)
- [x] `getMyGroupListFlow 예외처리 해주기`(data/../UserDataSource.kt)
