### ISSUE TITLE
그룹 상세보기 페이지 구현 추가 | TODO

### ISSUE THREAD

**Issue by soopeach** [boostcampwm-2022/android05-MoGakRun#36]
## 😆 관련 PR

- #35 

## 😲 개요

- [x] GroupDetailFragment 에서 uid를 사용하는 부분 DataStore에서 uid를 가져와서 적용하도록 변경
- [x] GroupDetailFragment 의 isLeader를 ViewModel로 이전
- [x] GroupDetailFragment 에서 세팅 메뉴 클릭 시 그룹 설정 페이지로 이동
- [x] GroupDetailFragment 에서 홍보하기 버튼 클릭 시 홍보하러 이동
- [x] GroupDetailFragment 에서 그룹 나가기 버튼 클릭 시 그룹 나가기
- [x] GroupDetailViewModel 의 getGroupNotificationsUseCase에서 사용하는 그룹 아이디 프레그먼트에서 받아오도록 변경
