### ISSUE TITLE
러닝 모드 TODO

### ISSUE THREAD

**Issue by yonghanJu** [boostcampwm-2022/android05-MoGakRun#53]
## 😆 관련 PR

- 관련 PR 제목 #0

## 😲 개요

- [ ] Tracking Mode 따라서 버튼 이미지 변경
- [ ] 도중에 gps 끈 경우 종료
- [x] px dp 변경
- [x] feat 모듈 생성
- [ ] 일시정지여도 lastLocation은 업데이트하도록 수정
